Rio-Yamazakii/welcome-to-team-arai-2025

database/migrations/2025_04_08_033350_create_laravel_forms_table.php
database/migrations/2025_04_08_033634_create_laravel_technologies_table.php
database/seeders/DatabaseSeeder.php
database/seeders/LaravelFormSeeder.php
database/seeders/LaravelTechnologiesSeeder.php

iss0006のクエリ基礎構文・マイグレーションファイルを作成しました。

iss0006_kurasawa クエリ基礎構文・マイグレーションファイル

---

app/Http/Controllers/LaravelFormController.php
app/Models/LaravelForm.php
app/Models/LaravelTechnology.php
database/migrations/2025_04_09_023745_add_deleted_at_to_laravel_forms_table.php
resources/views/laravel-forms/create.blade.php
resources/views/laravel-forms/edit.blade.php
resources/views/laravel-forms/index.blade.php
resources/views/laravel-forms/show.blade.php
resources/views/layouts/laravel-forms.blade.php
routes/web.php

iss0008_yanai

---

app/Http/Controllers/FormController.php
app/Models/LaravelForm.php
app/Models/LaravelTechnology.php
db_sql/iss6_db.sql
resources/views/index.blade.php
routes/web.php

iss0007 LaravelでDBのデータを取得して表示。

iss0007_kurasawa

---

package-lock.json
package.json
resources/js/app.js
resources/js/react/App.jsx
resources/js/react/components/Hello.jsx
resources/views/react.blade.php
routes/web.php
vite.config.js

iss0014_yanai

---

package-lock.json
package.json
resources/js/app.js
resources/js/app.jsx
resources/js/components/ExampleComponent.jsx
resources/views/react.blade.php
routes/web.php
vite.config.js

#14終了しました。

---

app/Http/Controllers/LaravelFormController.php
app/Models/LaravelForm.php
app/Models/LaravelTechnology.php
resources/views/form_tech_list.blade.php
routes/web.php

LaravelでDBのデータを取得して表示 #7
をやりました確認お願いします。

iss0007_Tada

---

package-lock.json
package.json
resources/js/react/App.jsx
resources/js/react/components/Greeting.jsx
resources/views/react.blade.php
vite.config.js

iss0015_yanaiの提出

---

app/Http/Controllers/LaravelFormController.php
app/Models/LaravelForm.php
resources/views/create_form.blade.php
resources/views/edit_form.blade.php
routes/web.php

Iss0008 _Tada

---

package-lock.json
package.json
resources/js/app.js
resources/js/app.jsx
resources/js/components/HelloReact.jsx
resources/views/react.blade.php
routes/web.php
vite.config.js

Iss0014 kurasawa　viteを使って既存のLaravelプロジェクトにReactを一部分導入

iss0014_kurasawa

---

package-lock.json
package.json
resources/js/app.js
resources/js/app.jsx
resources/js/components/HelloReact.jsx
resources/views/react.blade.php
routes/web.php
vite.config.js

iss0014_Tada

---

resources/js/app.jsx
resources/js/components/HelloMessage.jsx

Iss0015 Reactでpropsを使用したデータの受け渡し

iss0015_kurasawa

---

resources/js/app.jsx
resources/js/components/HelloChild.jsx

iss0015_Tada

---

app/Http/Controllers/Api/LaravelFormApiController.php
app/Providers/RouteServiceProvider.php
config/providers.php
routes/api.php

iss0017_yanai

---

package-lock.json
package.json
resources/css/app.css
resources/js/app.jsx
resources/js/components/ChildComponent.jsx
resources/js/components/ParentComponent.jsx
resources/views/reactprops.blade.php
vite.config.js

#16終了しました。

---

package-lock.json
package.json
resources/js/app.js
resources/js/app.jsx
resources/js/components/ExampleComponent.jsx
resources/views/react.blade.php
routes/web.php
vite.config.js

issue14が完了しました。
結果画面を添付するので、ご確認をお願いします。

Iss0014 ishihara

---

resources/css/app.css
resources/js/app.jsx
resources/js/components/Child.jsx
resources/js/components/HelloMessage.jsx
resources/views/react.blade.php
vite.config.js

iss0016_kurasawa

---

resources/js/react/App.jsx
resources/js/react/components/FormTable.jsx
resources/views/form-api.blade.php
routes/web.php

iss0018_yanai

---

app/Http/Controllers/Api/FormApiController.php
bootstrap/app.php
composer.json
composer.lock
config/sanctum.php
database/migrations/2025_04_11_032740_create_personal_access_tokens_table.php
routes/api.php

Iss0017 kurasawa

---

package-lock.json
package.json
postcss.config.js
resources/css/app.css
resources/js/app.jsx
resources/js/components/HelloChild.jsx
resources/views/react.blade.php
tailwind.config.js
vite.config.js

iss0016_Tada

---

app/Http/Controllers/FormController.php
bootstrap/app.php
composer.json
composer.lock
config/sanctum.php
database/migrations/2025_04_11_035748_create_personal_access_tokens_table.php
routes/api.php

#17終了しました。

---

resources/js/components/Forms.jsx
resources/js/hooks/useForms.js

Iss0020 kudo

---

app/Http/Controllers/LaravelFormController.php
bootstrap/app.php
composer.json
composer.lock
config/sanctum.php
database/migrations/2025_04_11_055942_create_personal_access_tokens_table.php
database/migrations/2025_04_11_060957_add_deleted_at_to_laravel_forms_table.php
routes/api.php

iss0017_Tada

---

app/Models/LaravelForm.php
database/migrations/2025_04_11_052140_add_birthplace_to_laravel_forms_table.php
database/migrations/2025_04_11_053602_drop_birthplace_from_laravel_forms_table.php
package-lock.json
package.json
resources/js/app.jsx
resources/js/components/FormTable.jsx
resources/views/react.blade.php

iss0018_kurasawa

---

package-lock.json
package.json
resources/js/app.jsx
resources/js/components/FormTable.jsx
resources/views/api.blade.php

#18が完了いたしました。
以下に結果画面を添付しましたので、ご確認をお願いします。

Iss0018 ishihara

---

resources/css/app.css
resources/js/app.jsx
resources/js/components/FormTable.jsx
resources/views/form_table.blade.php
routes/web.php

iss0018_Tada
